services:
  graphpaper.api:
    image: ch1mple/graphpaper-api:latest
    build:
      context: .
      dockerfile: GraphPaper.API/Dockerfile
    depends_on:
      graphpaper.database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection String
      - ConnectionStrings__DefaultConnection=Host=graphpaper.database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

      # AI & Auth Settings
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__Issuer=GraphPaper_Issuer
      - JWT__Audience=GraphPaper_Audience
      
      # Storage Settings (MinIO)
      # - MINIO_ENDPOINT=graphpaper.minio:9000
      # - MINIO_ACCESS_KEY=minioadmin 
      # - MINIO_SECRET_KEY=minioadmin
    ports:
      - "5000:5000"

  graphpaper.database:
    # IMPORTANT: Xài chuẩn pgvector image cho AI support
    image: pgvector/pgvector:pg16
    container_name: graphpaper_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pg_graph_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d graphpaper_db"]
      interval: 3s
      timeout: 3s
      retries: 10


  # CPU version (fallback if no compatible GPU)
  # graphpaper.parser:
  #   image: ghcr.io/docling-project/docling-serve-cpu:latest
  #   container_name: graphpaper_parser
  #   environment:
  #     - DOCLING_SERVE_ENABLE_UI=1
  #     - DOCLING_SERVE_ENABLE_DOCS=1
  #   ports:
  #     - "5001:5001"
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4G


  # GPU version (RTX 5060 Ti - Blackwell SM 120)
  graphpaper.parser:
    image: ghcr.io/docling-project/docling-serve-cu126:latest
    container_name: graphpaper_parser
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
      - DOCLING_SERVE_ENABLE_DOCS=1
      - TORCH_CUDA_ARCH_LIST=12.0
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "5001:5001"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  # Nào xài thì mở
  # graphpaper.minio:
  #   image: minio/minio
  #   container_name: graphpaper_minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio_data:/data

volumes:
  pg_graph_data:
  # minio_data: